# Generated by Django 2.1.7 on 2019-02-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_polloptionselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='current_status',
            field=models.CharField(choices=[('created', 'created'), ('open', 'open'), ('finished', 'finished'), ('archived', 'archived')], default='created', max_length=128),
        ),
    ]
