# Generated by Django 2.1.7 on 2019-02-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190226_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polloption',
            old_name='title',
            new_name='name',
        ),
    ]
