# Generated by Django 2.1.7 on 2019-02-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190227_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='title',
            new_name='name',
        ),
    ]
