# Generated by Django 2.1.7 on 2019-02-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190227_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
