# Generated by Django 2.1.7 on 2019-02-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
