# Generated by Django 2.1.7 on 2019-02-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_polloption_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloptionselection',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='polloptionselection',
            name='voter_user',
        ),
    ]
