# Generated by Django 2.1.7 on 2019-02-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190228_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvote',
            name='poll_option_selections',
            field=models.ManyToManyField(to='polls.PollOptionSelection'),
        ),
    ]
