# Generated by Django 2.1.7 on 2019-02-28 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0012_auto_20190228_0531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('poll', 'voter_user')},
        ),
    ]
